theme: jekyll-theme-slate
title: [New Horizons for Robot Learning: Closing the Innovation Loop]
description: [Workshop at the 2021 IEEE/RSJ International Conference on Intelligent Robots and Systems]
